name: C++ Quality Checks and Formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add deb-src entries and update
      - name: Add deb-src entries and update
        run: |
          sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu $(lsb_release -cs) main restricted universe multiverse
          deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs) main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-updates main restricted universe multiverse
          deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-backports main restricted universe multiverse
          deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-backports main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-security main restricted universe multiverse
          deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-security main restricted universe multiverse" >> /etc/apt/sources.list'
          sudo apt-get update -qq -o=Dpkg::Use-Pty=0 2> /dev/null

      # Install necessary build tools and dependencies
      - name: Install dependencies
        run: |
          echo "Installing build dependencies for ZNC..."
          sudo apt-get build-dep -qq -o=Dpkg::Use-Pty=0 -y znc znc-dev 2> /dev/null
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 -y cmake g++ make 2> /dev/null

      # Install ZNC latest
      - name: Install ZNC
        run: |
          echo "Cloning the ZNC repository..."
          git clone https://github.com/znc/znc.git --recursive /tmp/znc
          cd /tmp/znc
          echo "Building ZNC..."
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      # Set library path
      - name: Set library path
        run: |
          echo "Setting LD_LIBRARY_PATH..."
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/znc.conf
          sudo ldconfig

      # Configure and build the project
      - name: Build code
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      # Run tests and collect results
      - name: Run Tests
        run: |
          cd build
          ctest --output-json > test-results.json
          cp test-results.json $GITHUB_WORKSPACE/

      # Upload the test results as an artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-results.json
